excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Pods
disabled_rules: # rule identifiers to exclude from running
  - trailing_comma
  - trailing_whitespace
  - identifier_name
  - line_length
  - function_body_length
  - cyclomatic_complexity
  - type_body_length
  - unused_optional_binding
  - nesting
  - type_body_length
  - file_length
  - large_tuple
  - force_cast
cyclomatic_complexity:
  ignores_case_statements: true
