platform :ios, '13.0'

target 'Thesis Fitness App' do
  use_frameworks!
  
  pod 'Alamofire', '~> 5.4'
  pod 'ObjectMapper', '~> 4.2'
  pod 'SwiftyJSON', '~> 5.0'
  pod 'Kingfisher', '~> 5.15'
  pod 'SwiftyUserDefaults', '~> 5.0'
  pod 'lottie-ios'
  
  pod 'SVProgressHUD', '~> 2.2'
  
  pod 'FirebaseAnalytics'
  pod 'FirebaseAuth'
  pod 'FirebaseFirestore'
  
  pod 'GoogleSignIn'
  
  pod 'SwiftLint'
  
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
      end
    end
  end
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
        target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
        end
      end
    end
  end
end
